apiVersion: v1
kind: ConfigMap
metadata:
  name: mi-configmap-{{ .Values.name }}
  namespace: {{ .Values.namespace }}
data:
    host: "{{ .Values.configmap.host }}"
    port: "{{ .Values.configmap.port }}"
    database: "{{ .Values.configmap.database }}"
    user: "{{ .Values.configmap.user }}"

